export const ADD_LINE = 'stdout:ADD_LINE'
export const ADD_LINES = 'stdout:ADD_LINES'
export const CLEAR_SCREEN = 'stdout:CLEAR_SCREEN'

export const ADD_TO_CMD_HISTORY = 'stdout:ADD_TO_CMD_HISTORY'
export const SET_CMD_HISTORY_INDEX = 'stdout:SET_CMD_HISTORY_INDEX'
export const INCREMENT_CMD_HISTORY_INDEX = 'stdout:INCREMENT_CMD_HISTORY_INDEX'
export const DECREMENT_CMD_HISTORY_INDEX = 'stdout:DECREMENT_CMD_HISTORY_INDEX'

export const SET_BOOTING = 'stdout:SET_BOOTING'
export const SET_BOOTED = 'stdout:SET_BOOTED'
export const SET_PATH = 'stdout:SET_PATH'
export const SET_SPINNER_STAGE = 'stdout:SET_SPINNER_STAGE'
export const START_CMD = 'stdout:START_CMD'
export const STOP_CMD = 'stdout:STOP_CMD'
